"""Component 6 — format the RiskReport as a Markdown PR comment and post or
update it on the pull request."""

from datetime import datetime, timezone
from typing import List, Optional

import requests

from scorer.models import RiskLevel, RiskReport

GITHUB_API = "https://api.github.com"

_COMMENT_HEADER = "🏥 Clinical Risk Assessment"

_EMOJI = {
    RiskLevel.LOW: "🟢",
    RiskLevel.MEDIUM: "🟡",
    RiskLevel.HIGH: "🔴",
    RiskLevel.CRITICAL: "🚨",
}


def _bullets(items: List[str]) -> str:
    if not items:
        return "_None_"
    return "\n".join(f"- {item}" for item in items)


def _checklist(items: List[str]) -> str:
    if not items:
        return "_None_"
    return "\n".join(f"- [ ] {item}" for item in items)


def _modules_table(report: RiskReport) -> str:
    mods = report.signal.clinical_modules_touched
    if not mods:
        return "None"
    rows = ["| File | Domain | Risk Weight | +/- |", "|---|---|---|---|"]
    for m in mods:
        rows.append(
            f"| `{m.file_path}` | {m.domain} | {m.risk_weight} | "
            f"+{m.lines_added}/-{m.lines_removed} |"
        )
    return "\n".join(rows)


def _coverage_table(report: RiskReport) -> str:
    deltas = report.signal.coverage_deltas
    if not deltas:
        return "No clinical paths in coverage report"
    rows = ["| File | Coverage | Threshold | Status |", "|---|---|---|---|"]
    for d in deltas:
        status = "✅" if d.coverage_after >= report.coverage_threshold else "⚠️ below"
        rows.append(
            f"| `{d.file_path}` | {d.coverage_after:.0f}% | "
            f"{report.coverage_threshold:.0f}% | {status} |"
        )
    return "\n".join(rows)


def _issues_list(report: RiskReport) -> str:
    issues = report.signal.linked_issues
    if not issues:
        return "No linked issues found"
    lines = []
    for i in issues:
        kw = f" (keywords: {', '.join(i.clinical_keywords_found)})" if i.clinical_keywords_found else ""
        lines.append(f"- #{i.issue_number}: {i.title}{kw}")
    return "\n".join(lines)


def format_report(report: RiskReport) -> str:
    """Return the full markdown comment string."""
    score = report.score
    emoji = _EMOJI[score.level]
    timestamp = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S")

    reviewers = (
        _bullets([f"@{r}" for r in score.assigned_reviewers])
        if score.assigned_reviewers
        else "Standard review — no specific assignment"
    )

    teams = (
        _bullets([f"@{report.repo.split('/')[0]}/{t}" for t in score.assigned_teams])
        if score.assigned_teams
        else "_None_"
    )

    fallback_note = ""
    if score.fallback_used:
        fallback_note = "\n> ⚠ AI scorer unavailable — rule-based fallback used\n"

    return f"""## {_COMMENT_HEADER} — PR #{report.pr_number}

**Risk Level: {emoji} {score.level.value}**  &nbsp;|&nbsp;  **Score: {score.score}/10**
{fallback_note}
---

### Reasoning
{score.reasoning}

---

### Contributing Factors
{_bullets(score.contributing_factors)}

---

### Required Gates
{_checklist(score.recommended_gates)}

---

### Assigned Reviewers
{reviewers}

---

### Assigned Teams
{teams}

---

<details>
<summary>Signal breakdown</summary>

**Clinical modules touched:**

{_modules_table(report)}

**Coverage on clinical paths:**

{_coverage_table(report)}

**Linked issues:**

{_issues_list(report)}

</details>

---
<sub>Generated by Clinical Risk Scorer · {timestamp} UTC</sub>
"""


def _find_existing_comment(token: str, repo: str, pr_number: int) -> Optional[int]:
    """Return the comment id of a previous scorer comment, if any."""
    url = f"{GITHUB_API}/repos/{repo}/issues/{pr_number}/comments"
    headers = {
        "Authorization": f"Bearer {token}",
        "Accept": "application/vnd.github+json",
        "X-GitHub-Api-Version": "2022-11-28",
    }
    resp = requests.get(url, headers=headers, timeout=30)
    resp.raise_for_status()
    for comment in resp.json():
        if _COMMENT_HEADER in comment.get("body", ""):
            return comment["id"]
    return None


def post_or_update_comment(token: str, repo: str, pr_number: int, body: str) -> None:
    """
    Post the report as a PR comment. If a previous comment from this bot exists
    (identified by the '🏥 Clinical Risk Assessment' header), edit it in place;
    otherwise POST a new comment.
    """
    headers = {
        "Authorization": f"Bearer {token}",
        "Accept": "application/vnd.github+json",
        "X-GitHub-Api-Version": "2022-11-28",
    }
    existing_id = _find_existing_comment(token, repo, pr_number)

    if existing_id is not None:
        url = f"{GITHUB_API}/repos/{repo}/issues/comments/{existing_id}"
        resp = requests.patch(url, headers=headers, json={"body": body}, timeout=30)
    else:
        url = f"{GITHUB_API}/repos/{repo}/issues/{pr_number}/comments"
        resp = requests.post(url, headers=headers, json={"body": body}, timeout=30)
    resp.raise_for_status()
